name: file_parser
description: A file parser.
version: 1.0.0
repository: https://github.com/javaddict/file_parser

environment:
  sdk: ^3.8.1

dependencies:
  logger:

dev_dependencies:
  dart_cli:
    git: https://github.com/javaddict/dart_cli.git
  lints:
  test:
